name: Run tests and other quality checks

on: [pull_request]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ["3.8", "3.9", "3.10"]
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and the package
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
      - name: Run unit tests
        run: pytest --cov=qbench --cov-report=xml

  run_quality_cheks:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/checkout@v2
      - name: Install dependencies and the package
        run: |
          python -m pip install --upgrade pip
          pip install .[test,dev]
      - name: Quality checks
        run: |          
          mypy --ignore-missing-imports --install-types --non-interactive tests qbench
          flake8 --max-line-length=100 qbench
          black --check .
          isort --check-only --profile black qbench -c --diff
